import { useEffect,useMemo,useState } from 'react'
import {subjects,questions} from './data/questions.js'
const shuffle=a=>[...a].sort(()=>Math.random()-.5)
export default function App(){
 const [screen,setScreen]=useState('home'),[sid,setSid]=useState(''),[division,setDivision]=useState('全部'),[unit,setUnit]=useState('全部'),[level,setLevel]=useState('全部'),[count,setCount]=useState(10),[quiz,setQuiz]=useState([]),[i,setI]=useState(0),[picked,setPicked]=useState(null),[records,setRecords]=useState([])
 const [stats,setStats]=useState(()=>JSON.parse(localStorage.getItem('g7stats')||'{"done":0,"correct":0}'))
 useEffect(()=>localStorage.setItem('g7stats',JSON.stringify(stats)),[stats])
 const subject=subjects.find(s=>s.id===sid), subjectQ=questions.filter(q=>q.subject===sid), divisions=[...new Set(subjectQ.map(q=>q.division))], units=[...new Set(subjectQ.filter(q=>division==='全部'||q.division===division).map(q=>q.unit))]
 const filtered=useMemo(()=>subjectQ.filter(q=>(division==='全部'||q.division===division)&&(unit==='全部'||q.unit===unit)&&(level==='全部'||q.level===level)),[sid,division,unit,level])
 const current=quiz[i], score=records.filter(r=>r.correct).length, wrong=records.filter(r=>!r.correct)
 const home=()=>{setScreen('home');setSid('');setRecords([]);setPicked(null)}
 const open=s=>{if(questions.some(q=>q.subject===s.id)){setSid(s.id);setDivision('全部');setUnit('全部');setLevel('全部');setScreen('setup')}}
 const start=(random=true,source=filtered)=>{const list=random?shuffle(source):[...source];setQuiz(list.slice(0,Math.min(count,list.length)));setI(0);setPicked(null);setRecords([]);setScreen('quiz')}
 const next=()=>{const r={id:current.id,chosen:picked,correct:picked===current.answer};const n=[...records,r];setRecords(n);if(i+1===quiz.length){setStats(s=>({done:s.done+quiz.length,correct:s.correct+n.filter(x=>x.correct).length}));setScreen('result')}else{setI(i+1);setPicked(null)}}
 const retry=()=>start(false,wrong.map(r=>questions.find(q=>q.id===r.id)).filter(Boolean))
 return <div className="app"><header><div className="bar"><button className="brand" onClick={home}>學</button><div><h1>國一全科練習平台</h1><small>115學年度・七年級上學期</small></div>{screen!=='home'&&<button className="ghost" onClick={home}>全科首頁</button>}</div></header>
 {screen==='home'&&<main><section className="hero"><span>全科學習入口</span><h2>今天想挑戰哪一科？</h2><p>目前已建置國文、數學、社會地理、社會歷史與自然。英文入口將在取得教材後啟用。</p><div className="stats"><b>題庫 {questions.length} 題</b><b>已作答 {stats.done} 題</b><b>累計答對 {stats.correct} 題</b></div></section><div className="subject-grid">{subjects.map(s=>{const n=questions.filter(q=>q.subject===s.id).length;return <button key={s.id} disabled={!n} onClick={()=>open(s)} className={`subject ${n?'':'disabled'}`}><i style={{background:s.color}}>{s.icon}</i><div className="subject-title"><h3>{s.name}</h3><em>{n?`${n} 題`:'等待教材'}</em></div><p>{s.description}</p><strong style={{color:s.color}}>{n?'進入練習 →':'尚未啟用'}</strong></button>})}</div><div className="notice"><b>內容說明：</b>題目依使用者提供的教材範圍原創命題，非出版社官方題庫；不公開教材照片或整頁內容。</div></main>}
 {screen==='setup'&&subject&&<main><section className="subject-hero" style={{background:subject.color}}><span>七年級上學期</span><h2>{subject.name}練習</h2><p>{subject.description}</p></section><section className="panel"><div className="filters">{divisions.length>1&&<label>分科<select value={division} onChange={e=>{setDivision(e.target.value);setUnit('全部')}}><option>全部</option>{divisions.map(x=><option key={x}>{x}</option>)}</select></label>}<label>單元<select value={unit} onChange={e=>setUnit(e.target.value)}><option>全部</option>{units.map(x=><option key={x}>{x}</option>)}</select></label><label>難度<select value={level} onChange={e=>setLevel(e.target.value)}><option>全部</option><option>基礎</option><option>進階</option><option>挑戰</option></select></label><label>題數<select value={count} onChange={e=>setCount(Number(e.target.value))}><option>5</option><option>10</option><option>15</option><option>20</option></select></label></div><p className="available">符合條件：<b>{filtered.length}</b> 題</p><div className="actions"><button onClick={()=>start(false)} disabled={!filtered.length}>依序開始</button><button className="gold" onClick={()=>start(true)} disabled={!filtered.length}>隨機出題</button></div></section></main>}
 {screen==='quiz'&&current&&<main className="narrow"><div className="quiztop"><b>第 {i+1} 題，共 {quiz.length} 題</b><b>目前答對 {score} 題</b></div><div className="progress"><i style={{width:`${(i+1)/quiz.length*100}%`}}/></div><section className="panel"><div className="chips"><span>{current.division}</span><span>{current.unit}</span><span>{current.level}</span></div>{current.passage&&<blockquote>{current.passage}</blockquote>}<h2 className="question">{current.question}</h2><div className="options">{current.options.map((o,x)=>{let c='';if(picked!==null&&x===current.answer)c='correct';else if(picked===x)c='wrong';else if(picked!==null)c='muted';return <button className={c} disabled={picked!==null} onClick={()=>setPicked(x)} key={o}><b>{String.fromCharCode(65+x)}.</b>{o}</button>})}</div>{picked!==null&&<div className={`feedback ${picked===current.answer?'ok':'no'}`}><b>{picked===current.answer?'答對了！':`答錯了，正確答案是 ${String.fromCharCode(65+current.answer)}`}</b><p>{current.explanation}</p></div>}<div className="next"><button disabled={picked===null} onClick={next}>{i+1===quiz.length?'查看成績':'下一題'}</button></div></section></main>}
 {screen==='result'&&<main className="narrow"><section className="panel result"><h2>練習完成</h2><div className="score">{score}<small> / {quiz.length}</small></div><p>答對率 {Math.round(score/quiz.length*100)}%</p><div className="review"><h3>錯題回顧</h3>{!wrong.length?<div className="feedback ok">全部答對，表現很好！</div>:wrong.map((r,x)=>{const item=questions.find(q=>q.id===r.id);return <article key={r.id}><b>{x+1}. {item.question}</b><p className="red">你的答案：{String.fromCharCode(65+r.chosen)}. {item.options[r.chosen]}</p><p className="green">正確答案：{String.fromCharCode(65+item.answer)}. {item.options[item.answer]}</p><p>解析：{item.explanation}</p></article>})}</div><div className="actions"><button onClick={()=>setScreen('setup')}>返回本科</button>{wrong.length>0&&<button className="gold" onClick={retry}>重練錯題</button>}<button onClick={()=>start(true,quiz)}>再測一次</button></div></section></main>}</div>}
